USE JUNE_22 ;

ALTER TABLE DAY7 ADD COLUMN D7_FNAME VARCHAR(5) ;

ALTER TABLE DAY7 ADD COLUMN D7_FN VARCHAR(5) AFTER D5_ID ;


INSERT INTO DAY7 VALUES (56789 , "SDSDD" , "PQPQ","NM","MN");

SELECT SUM(Sanitizer) FROM PROD ;

SELECT 19115/12 ;

SELECT count(Sanitizer) FROM PROD ;

SELECT avg(Sanitizer) FROM PROD ;

SELECT 7 - 2 ;

SELECT 7 + 2 ;

SELECT 7 / 2 ;

SELECT * FROM PROD WHERE Month = "JUN" OR MONTH = "AUG" ;

SELECT * FROM PROD WHERE MONTH = "JUN" AND Moisturizer = 1580 ;

SELECT * FROM PROD WHERE NOT(MONTH = "JUN" AND Moisturizer = 1580) ;

INSERT INTO DAY7 VALUES 
(45678 , "AWAW" , "BNBN","ERTY" , "JKJK") ,
(2315 , "VBVB", "YUIOP","XCV","45RT");


INSERT INTO DAY7 (D5_ID, D7_FN, D5_CITY) VALUES 
(45678 , "AWAW" , "BNBN") ,
(2315 , "XCV","45RT");


SELECT * FROM JUNE_23_2 WHERE Order_Priority = "H" ;

show databases ;

USE RAJESH ;

DESCRIBE TITANIC ;

SELECT * FROM TITANIC WHERE AGE = 27 AND SEX = "FEMALE" ;


SELECT COUNT(Sex) FROM TITANIC ;

SELECT * FROM TITANIC WHERE AGE = 27 AND SibSp < 1 ; 

SELECT * FROM TITANIC WHERE NOT(AGE = 27 AND SibSp < 1) ;

SELECT * FROM TITANIC WHERE NOT(AGE = 27 AND SibSp < 1) ORDER BY AGE ;

SELECT * FROM TITANIC WHERE AGE = 27 OR SIBSP = 0 ;

SELECT * FROM TITANIC WHERE AGE = 27 OR SIBSP = 0 ORDER BY AGE;

SELECT * FROM TITANIC WHERE NOT(AGE = 27 OR SIBSP = 0) ORDER BY AGE;

SELECT * FROM TITANIC WHERE AGE = 24 OR AGE = 27 OR AGE = 34 ;

SELECT * FROM TITANIC WHERE AGE = 24 OR AGE = 27 OR AGE = 34
ORDER BY AGE  ;

SELECT * FROM TITANIC WHERE AGE IN (23,89,67,34,56,12) ORDER BY AGE;

SELECT * FROM TITANIC WHERE AGE NOT IN (23,89,67,34,56,12) ORDER BY AGE;

SELECT * FROM TITANIC WHERE AGE BETWEEN 24 AND 36 ORDER BY AGE ;

SELECT * FROM TITANIC WHERE AGE BETWEEN 34 AND 26 ORDER BY AGE ;

SELECT * FROM TITANIC WHERE NAME BETWEEN "DO" AND "P" ORDER BY NAME ;

SELECT * FROM TITANIC WHERE NAME LIKE "H%" ORDER BY NAME; # Starts with

SELECT * FROM TITANIC WHERE NAME LIKE "%H" ORDER BY NAME;  # ends with

SELECT * FROM TITANIC WHERE NAME LIKE "%Han%" ORDER BY NAME;  # ends with

SELECT * FROM TITANIC WHERE NAME LIKE "m%n" ORDER BY NAME;  # ends with

select * , 
case when age > 18 then "ELIGIBLE"
     WHEN AGE = 18 THEN " @fIRST@ "
	ELSE "  !!!!SORRYY NOT ALLOWED ...."
    END AS CASE_COLUMN FROM TITANIC ;

CREATE DATABASE Banking ;

USE Banking ;
CREATE TABLE CUSTOMERS
(
 CUST_ID INT PRIMARY KEY ,
 CUST_FNAME VARCHAR(20),
 CUST_LNAME VARCHAR(20),
 CUST_EMAIL VARCHAR(30),
 CUST_PHONE VARCHAR(10),
 CUST_ACCOUNT_DATE date
 );
 
INSERT INTO CUSTOMERS VALUES (1234 , "PRIYA","SHAH","PR@GMAIL.COM","1234567899",
 "2026-06-25");
 
INSERT INTO CUSTOMERS VALUES (5678 , "DIYA","PATEL","DP@GMAIL.COM","9876543211",
 "2026-06-22");
 
 
UPDATE CUSTOMERS SET CUST_LNAME = "MISHRA" WHERE CUST_ID = 9876;

SELECT CUST_ID, CUST_FNAME, CUST_LNAME, 
CASE WHEN CUST_LNAME = "Patel" then "VALID"
ELSE "   Not Valid  " end as describe_last
,CUST_EMAIL, CUST_PHONE, CUST_ACCOUNT_DATE from customers ;

CREATE TABLE CUSTOMERS2
(
 CUST2_ID INT PRIMARY KEY ,
 CUST2_FNAME VARCHAR(20),
 CUST2_LNAME VARCHAR(20),
 CUST2_EMAIL VARCHAR(30),
 CUST2_PHONE VARCHAR(10),
 CUST2_ACCOUNT_DATE date,
 check (CUST2_LNAME = "PATEL") 
 );
 
 
select * from bank limit 17 ;
 
 
select * from bank where gender = "f" limit 5 ;
 
select * from bank where gender = "f" and Customer_Age = 61 limit 6 ;
  
select * from bank where gender = "f" and Customer_Age = 61 limit 6 
  offset 2;
  
select Dependent_count , rank() over(order by Dependent_count) as dff
from bank ;

select Dependent_count , rank() over(order by Dependent_count) as dff
from bank ;
 
select CUST_ID, CUST_FNAME, CUST_LNAME,CUST_ACCOUNT_DATE , 
date_format(CUST_ACCOUNT_DATE , "%W %d %M %Y") date_formatt FROM CUSTOMERS ;

select CUST_ID, CUST_FNAME, CUST_LNAME,CUST_ACCOUNT_DATE , 
date_format(CUST_ACCOUNT_DATE , "%d %M %Y %W") date_formatt FROM CUSTOMERS ;

USE JULY_1 ;

CREATE TABLE DAT3
(
D3_ID INT PRIMARY KEY ,
D3_FNAME VARCHAR(23),
D3_AGE INT
);

SELECT * FROM DAT3 WHERE D3_AGE = (SELECT W5_ENR FROM WE5 WHERE W5_ENR = 23) ;


SELECT * FROM DAT3 WHERE D3_AGE > (SELECT AVG(D3_AGE) FROM DAT3 ) ;

SELECT AVG(D3_AGE) FROM DAT3 ;

SELECT facenumber_in_poster ,COUNT(imdb_ID) FROM imdb_movies_dataset GROUP BY facenumber_in_poster ;

select age,count(PassengerId) from titanic group by Age  order by age;

select age,count(PassengerId) from titanic group by Age having 
 count(PassengerId) >= 2 order by age;
 
 
 CREATE TABLE RECO
 (
 R_IND INT PRIMARY KEY ,
 R_AGE INT ,
 R_GENDER ENUM("M","F","O")
 );

CREATE DATABASE JUNE_30 ;

USE JUNE_30 ;

CREATE TABLE PRENTT
(
 P_ID INT PRIMARY KEY AUTO_INCREMENT,
 P_NAME VARCHAR(20),
 P_AGE INT
 );
 
 CREATE TABLE CHILL
 (
  CH_ID INT PRIMARY KEY ,
  CH_LNAME VARCHAR(34),
  CH_P INT,
  FOREIGN KEY (CH_P) REFERENCES PRENTT(P_ID)
  );
  
  
SELECT * FROM CHILL ;
  
SELECT * FROM PRENTT INNER JOIN CHILL ON
PRENTT.P_ID = CHILL.CH_P ;


SELECT * FROM PRENTT LEFT JOIN CHILL ON 
PRENTT.P_ID = CHILL.CH_P ;


SELECT * FROM chill right JOIN Prentt ON 
PRENTT.P_ID = CHILL.CH_P ;

select * from chill full join  prentt ;

CREATE TABLE SDF
(
S_ID INT PRIMARY KEY AUTO_INCREMENT,
S_NAME VARCHAR(20),
S_AGE int
);

SELECT * , SUM(S_ID) OVER (ORDER BY S_AGE) AS DF FROM SDF ;


SELECT * , RANK() OVER (ORDER BY S_AGE) FROM SDF ;

SELECT * , RANK() OVER (ORDER BY S_AGE DESC) FROM SDF ;

SELECT * , SUM(CH_ID) OVER (partition by CH_P) FROM CHILL ;

SELECT 4545+8989 ;

SELECT * FROM SDF ;

SELECT  S_NAME, S_AGE FROM SDF ;

SELECT  S_NAME, S_AGE FROM SDF WHERE S_AGE IN (7,4) ;

USE JULY_1 ;

CREATE TABLE TITA_22 SELECT * FROM TITANIC WHERE age = 22 ;

CREATE VIEW AGE_35 AS SELECT PassengerId, Survived, Pclass, Name, Sex, 
Age,Fare, Embarked FROM TITANIC ;


DELIMITER //
CREATE PROCEDURE PRO_8(IN R VARCHAR(10))
BEGIN
  SELECT * FROM TITANIC WHERE Sex = R ;
END //
DELIMITER ;

CREATE USER "TEENA"@"LOCALHOST" IDENTIFIED BY "456" ;

GRANT SELECT, DELETE ON JULY_1.*  TO"TEENA"@"LOCALHOST" ;

REVOKE SELECT, DELETE ON JULY_1.*  FROM "TEENA"@"LOCALHOST" ;

use april_8 ;

describe abc ;

delete from def where D_A = 11 ;

select * from def ;

rollback ;

commit;

delete from xyz where Y_ENR = 6767 ;

ROLLBACK ;

SAVEPOINT DLL ;

SELECT * FROM XYZ;

INSERT INTO XYZ VALUES(6767 , "RRRRR",22); 

ROLLBACK TO DLL ;


